export const jwtTokenKey = 'jwt=token';
export const jwtDataKey = 'jwt=data';
export const currentTest = 'test=current';
export const userLanguageKey = 'language';
export const testGrammarUserAnswers = 'test=grammarUserAnswers';
export const testListeningUserAnswers = 'test=listeningUserAnswers';
export const testEassyUserAnswers = 'test=essayUserAnswers';
export const testSpeakingAnswers = 'test=speakingUserAnswers';
export const testSpeakingFile = 'test=speakingFile';
