name: docker CI

on:
  push:
    branches: [ develop ]

  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build ./ -t docker_frontend
              
